spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loja
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  rabbitmq:
    addresses: amqps://iriisfhm:crP_OvtGU67-WxQ1ER7zeRPLBapMJtj1@shrimp.rmq.cloudamqp.com/iriisfhm
    queue: ms.categoria